# A periodic workflow to publish the apio mkDocs at /docs dir to the github
# Pages of this repo.

name: publish-docs

on:
  push:
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/publish-docs.yaml"

  schedule:
    - cron: "0 * * * *" # Every hour at minute 0

  workflow_dispatch: # 👈 enables manual trigger via GitHub UI

permissions:
  contents: write # 👈 Needed for mkdocs gh-deploy to push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install  mkdocs-material

      - name: Build site (strict mode)
        run: |
          mkdocs build --strict

      - name: Deploy to GitHub Pages
        # Push also if no change.
        run: |
          # set -x
          # echo '```' >> $GITHUB_STEP_SUMMARY
          mkdocs gh-deploy --force 2>&1 | tee >> $GITHUB_STEP_SUMMARY
          # echo '```' >> $GITHUB_STEP_SUMMARY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
